### PR TITLE
Damien Nassim

### PR DESCRIPTION
**Pull request by nassimaugsburg**

### CODE REVIEW

**Review by marcWalpen — CHANGES_REQUESTED** [review]
Please change the file and put only our first name

**Review by selligZeittom — CHANGES_REQUESTED** [review]
add a mutex please

**Review by selligZeittom — CHANGES_REQUESTED** [review]
MUTEEEEEEEEEEEEEEEEEEEEEEEEX

**Review by marcWalpen — CHANGES_REQUESTED** [review]
You forgot to enable the EventRecorder for everything

**Review by selligZeittom — APPROVED** [review]

**Review by marcWalpen — APPROVED** [review]
good work

**Pull request merged**
